AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - spec/dummy/**/*
  TargetRubyVersion: 2.3


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'


Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true


Naming/FileName:
  Exclude:
    - Appraisals
    - Gemfile
    - Rakefile
    - rails-rfc6570.gemspec


Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
