dist: bionic
language: ruby
bundler_args: "--without development"
rvm:
  - 2.7
  - 2.6
  - 2.5
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_head.gemfile
jobs:
  include:
    - rvm: 2.7
      gemfile: 'Gemfile'
      script:
        - bundle exec rubocop --parallel --color 
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
