dist: xenial
language: ruby
bundler_args: "--without development"
rvm:
- 2.6.4
- 2.5.6
- 2.4.7
gemfile:
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
- gemfiles/rails_5.2.gemfile
- gemfiles/rails_6.0.gemfile
- gemfiles/rails_head.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/rails_head.gemfile
  - rvm: 2.4.7
    gemfile: gemfiles/rails_head.gemfile

