sudo: false
dist: trusty
language: ruby
bundler_args: --without development
rvm:
- 2.5.0
- 2.4.3
- 2.3.5
gemfile:
- gemfiles/rails_5.2.gemfile
- gemfiles/rails_5.1.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_head.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/rails_head.gemfile
  exclude:
  - rvm: 2.3.5
    gemfile: gemfiles/rails_head.gemfile
before_install:
  - gem install bundler
