dist: bionic
language: ruby
bundler_args: "--without development"
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_head.gemfile
jobs:
  include:
    - name: rubocop
      rvm: 2.7.1
      gemfile: []
      script:
        - bundle exec rubocop --parallel --color
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
