language: ruby
bundler_args: --without development
rvm:
- '2.1'
- '2.0'
- 1.9.3
- jruby
- rbx-2
gemfile:
- gemfiles/Gemfile.rails-4-2
- gemfiles/Gemfile.rails-4-1
- gemfiles/Gemfile.rails-4-0
matrix:
  allow_failures:
    - rvm: rbx-2
    - gemfile: gemfiles/Gemfile.rails-4-2
