language: ruby
bundler_args: --without development
rvm:
- '2.4.1'
- '2.3.4'
- '2.2.7'
gemfile:
- gemfiles/Gemfile.rails-head
- gemfiles/Gemfile.rails-5-1
- gemfiles/Gemfile.rails-5-0
- gemfiles/Gemfile.rails-4-2
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
before_install:
  - gem install bundler
