name: release

on:
  push:
    tags:
      - v*

jobs:
  rubygems:
    if: github.repository == 'jgraichen/rails-rfc6570'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: rubygems/release-gem@v1
